# Generated by Django 5.2.6 on 2025-09-30 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_alter_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
