# Generated by Django 5.2.6 on 2025-09-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_alter_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(default='shewalevedant993@gmail.com', max_length=122),
            preserve_default=False,
        ),
    ]
