# Generated by Django 5.2.6 on 2025-09-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_alter_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='feedback',
            field=models.TextField(default='This is feedback', max_length=1000),
            preserve_default=False,
        ),
    ]
